version: '2.2'
services:

  mysql:
    image: ${MYSQL_IMAGE_NAME}
    container_name: ${MYSQL_HOST}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      # MySQL data directory
      - ./_host-volumes/dbdata:/var/lib/mysql
      # MySQL config directory
      - ./_host-volumes/dbconfig:/etc/mysql/conf.d
